name: Deploy Subgraph - Local

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      SUBGRAPH_NAME: thetruthpost-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build subgraph
        run: |
          export NETWORK_NAME=goerli
          yarn codegen
          yarn build

      - name: Create and start Docker containers
        run: |
          export ETHEREUM_NODE_PROVIDER=${{ secrets.ETHEREUM_NODE_PROVIDER }}
          docker-compose up -d

      - name: Wait for containers to start
        run: |
          while [[ "$(docker-compose ps -q | xargs docker inspect --format '{{.State.Status}}')" != "running" ]]; do sleep 2; done

      - name: Create and deploy a local Subgraph
        run: yarn create-local $SUBGRAPH_NAME

      - name: Deploy a local Subgraph
        run: yarn deploy-local $SUBGRAPH_NAME --version-label 0.0.1

      - name: Post subgraph URL to pull request
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            A new subgraph deployment has been created for this pull request.
            You can access it at: https://localhost:8000/subgraphs/name/$SUBGRAPH_NAME/graphql

      - name: Stop Docker containers
        if: github.event.pull_request.merged == true || github.event.pull_request.closed == true
        run: docker-compose down
